In [1]:
import pandas as pd
import numpy as np

df = pd.read_csv('heartdisease.csv')
df.drop(columns='education',inplace=True)
df

,male,age,currentSmoker,cigsPerDay,BPMeds,prevalentStroke,prevalentHyp,diabetes,totChol,sysBP,diaBP,BMI,heartRate,glucose,TenYearCHD
0,1,39,0,0.0,0.0,0,0,0,195.0,106.0,70.0,26.97,80.0,77.0,0
1,0,46,0,0.0,0.0,0,0,0,250.0,121.0,81.0,28.73,95.0,76.0,0
2,1,48,1,20.0,0.0,0,0,0,245.0,127.5,80.0,25.34,75.0,70.0,0
3,0,61,1,30.0,0.0,0,1,0,225.0,150.0,95.0,28.58,65.0,103.0,1
4,0,46,1,23.0,0.0,0,0,0,285.0,130.0,84.0,23.10,85.0,85.0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4233,1,50,1,1.0,0.0,0,1,0,313.0,179.0,92.0,25.97,66.0,86.0,1
4234,1,51,1,43.0,0.0,0,0,0,207.0,126.5,80.0,19.71,65.0,68.0,0
4235,0,48,1,20.0,NaN,0,0,0,248.0,131.0,72.0,22.00,84.0,86.0,0
4236,0,44,1,15.0,0.0,0,0,0,210.0,126.5,87.0,19.16,86.0,NaN,0
4237,0,52,0,0.0,0.0,0,0,0,269.0,133.5,83.0,21.47,80.0,107.0,0

In [2]:
from sklearn.svm import SVC

model = SVC(C=10)

data = df[['age','prevalentHyp','sysBP','diaBP']] 
y = df['TenYearCHD']

In [3]:
from sklearn.model_selection import train_test_split

x_train,x_test,y_train,y_test = train_test_split(data,y,test_size=0.4,random_state=0)

model.fit(x_train,y_train)

pred = model.predict(x_test)

model.score(x_test,y_test)

0.8555424528301887

In [4]:
from sklearn.model_selection import cross_val_score

acc = cross_val_score(model,data,y,cv=10)
acc.mean()
#--> AVERAGE ACCURACY

0.8482776885677327

In [5]:
from sklearn import metrics

metrics.confusion_matrix(y_test,pred,labels=(1,0))

#--> SINCE THE VALUES IN TP AND FP ARE ZERO WE GET A ZERO DIVISION WARNING BELOW

array([[   0,  245],
       [   0, 1451]], dtype=int64)

In [6]:
print(metrics.classification_report(y_test,pred))

              precision    recall  f1-score   support

           0       0.86      1.00      0.92      1451
           1       0.00      0.00      0.00       245

    accuracy                           0.86      1696
   macro avg       0.43      0.50      0.46      1696
weighted avg       0.73      0.86      0.79      1696

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1245: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1245: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1245: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))